### PR TITLE
Added mkcert ssl key and certificate for https Server

### PR DESCRIPTION
**Pull request by PRISHIta123**

### CODE REVIEW

**Comment by datacrystals** [comment]
Fantastic, thanks! Do you want to go over this on our Sunday call?

**Review by datacrystals — COMMENTED** [review]
Hmm - looks like we should .gitignore the keys. Apologies for the delay in getting back to you.

**Comment by PRISHIta123** [comment]
If we use .gitignore to remove the keys, any new user who clones/forks the repository will not have access to them (and would have to generate a new key). Instead, if we expose the keys using a config file, that could be a security issue too. 

So I have added an installation script to automatically generate a new key using the packages each time, but I suppose this is not the most feasible method. Is there any other way we can try to do this?

**Comment by datacrystals** [comment]
I think that's the most sensible solution, I think it makes sense to
generate new certs for every install. From my experience, every time you
install something with an https web server, it'll just generate some certs.
If the user wants to set up their own certs, then they can do that by
copying in the files, so I think this is fine. By any chance, is there a
check in the python code to see if the cert files exist? It would probably
be helpful to have it print out an error message if they don't exist.
(Unless you've beaten me to it on this - apologies if that's the case.)

**Comment by PRISHIta123** [comment]
No I don't there is a check for this (since the paths are directly added in the APIserver initialization). I think a try except block around it might work...

**Comment by datacrystals** [comment]
That sounds like a good plan, please let me know how it goes.

**Review by datacrystals — APPROVED** [review]
Looks good!

**Comment by PRISHIta123** [comment]
Tom, should I merge this pull request or make any other changes?

**Comment by datacrystals** [comment]
We should probably test it first - or have you already tested it?

**Comment by PRISHIta123** [comment]
It seems to be working fine if it finds the key and certificate. If not it returns a FileNotFound Error (from the try-except block):

image

**Comment by datacrystals** [comment]
Hmm, perhaps the exception isn't catching that error? Also prior to having
a try except, it would probably be good to have it check with something
like os.path.exists, and based on that, autogenerate the file. That way,
you don't have to generate a cert in an exception. Then make the exception
on the loading part log an error in the log saying something like could not
load key file or something like that.

**Comment by PRISHIta123** [comment]
I have updated the code to generate a new key and cert using the installation script if they don't already exist.

**Pull request merged**
